# Generated by Django 5.2.9 on 2025-12-04 06:09

import django_resized.forms
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('utype', models.CharField(max_length=10)),
                ('cname', models.CharField(default='N/A', max_length=100)),
                ('caddr', models.TextField(blank=True, default='N/A', null=True)),
                ('uname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('ph_no', models.BigIntegerField(unique=True)),
                ('passkey', models.CharField(max_length=50)),
                ('location', models.CharField(default='N/A', max_length=50)),
                ('addr', models.TextField(blank=True, default='N/A', null=True)),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to=service.models.rename_user_photo)),
            ],
        ),
    ]
