# Generated by Django 5.2.9 on 2025-12-04 09:56

import django_resized.forms
import service.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to=service.models.rename_user_photo),
        ),
    ]
